/** Unsplash / Picsum URLs — mỗi tour một ảnh, khớp chủ đề điểm đến. */
const U = (id: string) => `https://images.unsplash.com/${id}?w=800&q=80`;
const P = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

export const TOUR_STOCK = {
  beachSunset: U('photo-1507525428034-b723cf961d3e'),
  beachTropical: U('photo-1544551763-46a013bb70d5'),
  beachCliff: U('photo-1505142468610-359e7d316be0'),
  beachKayak: U('photo-1530549387789-4c1017266635'),
  coastRoad: U('photo-1559827260-dc66d52bef19'),
  sandDunes: U('photo-1472214103451-9374bd1c798e'),
  islandAerial: P('vietnam-island-aerial'),
  resortPool: U('photo-1571896349842-33c89424de2d'),
  resortVilla: U('photo-1573843981267-be1999ff37cd'),
  resortInterior: U('photo-1582719478250-c89cae4dc85b'),
  mountain: U('photo-1519681393784-d120267933ba'),
  mountainPeak: U('photo-1501594907352-04cda38ebc29'),
  mountainSunset: U('photo-1506905925346-21bda4d32df4'),
  trek: U('photo-1500534314209-a25ddb2bd429'),
  forest: U('photo-1469474968028-56623f02e42e'),
  forestPath: U('photo-1441974231531-c6227db76b6e'),
  lake: U('photo-1476514525535-07fb3b4ae5f1'),
  lakeDock: U('photo-1439066615861-d1af74d74000'),
  cave: U('photo-1518548419970-58e3b4079ab2'),
  bay: U('photo-1552733407-5d5c46c3bb3b'),
  heritage: U('photo-1559592413-7cec4d0cae2b'),
  oldTown: U('photo-1523906834658-6e24ef2386f9'),
  mekong: P('mekong-delta-vietnam'),
  city: U('photo-1488646953014-85cb44e25828'),
  tokyo: U('photo-1540959733332-eab4deabeeaf'),
  paris: U('photo-1502602898657-3e91760cbb34'),
  seoul: U('photo-1493976040374-85c8e12f0c0e'),
  singapore: U('photo-1528127269322-539801943592'),
  yacht: U('photo-1567894340315-735d7c361db0'),
  bali: P('bali-rice-terrace'),
  santorini: P('santorini-greece-blue'),
  dubai: P('dubai-skyline-desert'),
  golf: P('danang-golf-resort'),
  dalat: P('dalat-pine-hills'),
  sapaTerrace: P('sapa-rice-terrace'),
  fansipan: P('fansipan-cable-car'),
  goldenBridge: P('ba-na-golden-bridge'),
  vinpearl: P('nha-trang-vinpearl'),
  phuQuocBeach: P('phu-quoc-beach-sao'),
  quyNhon: P('quy-nhon-ky-co'),
  lySon: P('ly-son-island-vietnam'),
  conDao: P('con-dao-beach'),
  phanThiet: P('phan-thiet-beach'),
  hoTram: P('ho-tram-resort'),
  catBaBay: P('cat-ba-lan-ha-bay'),
  namDu: P('phu-quoc-nam-du-island'),
  default: U('photo-1469854523086-cc02fe5d8800'),
} as const;

/** Ảnh riêng theo tên tour — ưu tiên khi fallback frontend. */
export const TOUR_IMAGE_BY_NAME: Record<string, string> = {
  'fansipan trek': TOUR_STOCK.fansipan,
  'hồ ba bể': TOUR_STOCK.lakeDock,
  'hang én': TOUR_STOCK.cave,
  'cát bà trek': TOUR_STOCK.mountainPeak,
  'mai châu': TOUR_STOCK.forest,
  'tà năng': TOUR_STOCK.mountain,
  'lang biang': TOUR_STOCK.dalat,
  'bạch mộc': TOUR_STOCK.mountainSunset,
  'bản cát cát': TOUR_STOCK.sapaTerrace,
  'kẻm chim': TOUR_STOCK.forestPath,
  'côn đảo trek': TOUR_STOCK.conDao,
  'hải vân': TOUR_STOCK.coastRoad,
  'maldives': TOUR_STOCK.resortVilla,
  'dubai': TOUR_STOCK.dubai,
  'santorini': TOUR_STOCK.santorini,
  'vinpearl luxury': TOUR_STOCK.vinpearl,
  'phú quốc regent': TOUR_STOCK.phuQuocBeach,
  'golf & resort': TOUR_STOCK.golf,
  'tokyo premium': TOUR_STOCK.tokyo,
  'seoul suite': TOUR_STOCK.seoul,
  'paris champs': TOUR_STOCK.paris,
  'bali ubud': TOUR_STOCK.bali,
  'phuket yacht': TOUR_STOCK.yacht,
  'marina bay': TOUR_STOCK.singapore,
  'vinwonders phú quốc': TOUR_STOCK.resortInterior,
  'đà lạt thú vui': TOUR_STOCK.dalat,
  'vinpearl nha trang': TOUR_STOCK.resortPool,
  'hội an lồng đèn': TOUR_STOCK.oldTown,
  'huế di sản': TOUR_STOCK.heritage,
  'mỹ tho': TOUR_STOCK.mekong,
  'cáp treo fansipan': TOUR_STOCK.fansipan,
  'hạ long du thuyền': TOUR_STOCK.bay,
  'tam đảo': TOUR_STOCK.lake,
  'bà nà hills': TOUR_STOCK.goldenBridge,
  'cần thơ': TOUR_STOCK.mekong,
  'quy nhơn biển xanh': TOUR_STOCK.quyNhon,
  'nha trang biển xanh': TOUR_STOCK.beachTropical,
  'mũi né resort': TOUR_STOCK.sandDunes,
  'phú quốc sunset': TOUR_STOCK.beachSunset,
  'quy nhơn kỳ co': TOUR_STOCK.quyNhon,
  'lý sơn snorkeling': TOUR_STOCK.lySon,
  'côn đảo biển': TOUR_STOCK.conDao,
  'phan thiết biển dừa': TOUR_STOCK.phanThiet,
  'đà nẵng mỹ khê': TOUR_STOCK.coastRoad,
  'hội an an bàng': TOUR_STOCK.oldTown,
  'hồ tràm': TOUR_STOCK.hoTram,
  'cát bà biển': TOUR_STOCK.catBaBay,
  'phú quốc nam du': TOUR_STOCK.namDu,
};

/** Ảnh riêng theo điểm đến (không trùng lặp). */
export const DESTINATION_IMAGE: Record<string, string> = {
  'đà lạt': TOUR_STOCK.dalat,
  'sa pa': TOUR_STOCK.sapaTerrace,
  'hạ long': TOUR_STOCK.bay,
  'phú quốc': TOUR_STOCK.phuQuocBeach,
  'nha trang': TOUR_STOCK.beachTropical,
  'đà nẵng': TOUR_STOCK.coastRoad,
  'hội an': TOUR_STOCK.oldTown,
  'mũi né': TOUR_STOCK.sandDunes,
  'maldives': TOUR_STOCK.resortVilla,
  'dubai': TOUR_STOCK.dubai,
  'santorini': TOUR_STOCK.santorini,
  'phuket': TOUR_STOCK.yacht,
  'bali': TOUR_STOCK.bali,
  'tokyo': TOUR_STOCK.tokyo,
  'seoul': TOUR_STOCK.seoul,
  'paris': TOUR_STOCK.paris,
  'singapore': TOUR_STOCK.singapore,
  'bangkok': TOUR_STOCK.seoul,
  'quy nhơn': TOUR_STOCK.quyNhon,
  'lý sơn': TOUR_STOCK.lySon,
  'côn đảo': TOUR_STOCK.conDao,
  'phan thiết': TOUR_STOCK.phanThiet,
  'huế': TOUR_STOCK.heritage,
  'cần thơ': TOUR_STOCK.mekong,
  'quảng bình': TOUR_STOCK.cave,
  'cát bà': TOUR_STOCK.catBaBay,
};

export const CATEGORY_IMAGE: Record<string, string> = {
  Adventure: TOUR_STOCK.mountain,
  Luxury: TOUR_STOCK.resortVilla,
  Family: TOUR_STOCK.beachTropical,
  Beach: TOUR_STOCK.beachSunset,
};

export function getTourStockByName(tourName: string | null | undefined): string | null {
  if (!tourName?.trim()) return null;
  const lower = tourName.trim().toLowerCase();
  const key = Object.keys(TOUR_IMAGE_BY_NAME).find(k => lower.includes(k));
  return key ? TOUR_IMAGE_BY_NAME[key] : null;
}
